---
name: "Dependency Check Config"

# スキャン対象の設定
scan:
  # フロントエンドの依存関係をスキャン
  front:
    path: front
    package-manager: pnpm
    lock-file: pnpm-lock.yaml
    ignore-patterns:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/build/**"
      - "**/coverage/**"
      - "**/.next/**"
      - "**/out/**"
      - "**/test/**"
      - "**/tests/**"
      - "**/__tests__/**"

  # バックエンドの依存関係をスキャン
  back:
    path: back
    package-manager: go
    lock-file: go.sum
    ignore-patterns:
      - "**/vendor/**"
      - "**/test/**"
      - "**/tests/**"

# スキャン設定
settings:
  # 脆弱性の重大度レベル（medium以上を検出）
  severity-threshold: medium
  # スキャン頻度（週次実行）
  schedule: weekly
  # 自動更新の設定
  auto-update:
    enabled: true
    # セマンティックバージョニングに従う
    versioning: semver
    # パッチとマイナーバージョンの更新のみ自動マージ
    allowed-updates:
      - type: patch
      - type: minor
  # プルリクエストの設定
  pull-request:
    enabled: true
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "team:security"
    # セキュリティ更新の優先度を設定
    security-updates:
      priority: high
      auto-merge: true
      require-review: true
