---
name: 大学入試科目ナビ
description: 大学入試科目ナビのIssueトラッカー
body:
  - type: markdown
    attributes:
      value: |
        Issueを作成する前に、既存のIssueを確認してください。
  - type: dropdown
    attributes:
      label: Issue Type
      options:
        - バグ報告
        - 機能要望
        - ドキュメント
        - パフォーマンス
        - セキュリティ
        - アクセシビリティ
        - その他
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 優先度
      options:
        - 高
        - 中
        - 低
    validations:
      required: true
  - type: textarea
    attributes:
      label: 概要
      description: 問題や要望の簡潔な説明
      placeholder: 問題や要望の概要を入力してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
      description: バグの場合、問題を再現するための手順
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 期待される動作
      description: 期待される動作の説明
      placeholder: 期待される動作を入力してください
    validations:
      required: false
  - type: textarea
    attributes:
      label: 環境情報
      description: 使用している環境の情報
      placeholder: |
        - OS:
        - ブラウザ:
        - バージョン:
    validations:
      required: false
  - type: textarea
    attributes:
      label: 追加情報
      description: その他の関連情報
      placeholder: その他の関連情報を入力してください
    validations:
      required: false
blank_issues_enabled: false
contact_links:
  - name: 質問・相談
    url: https://github.com/yourusername/UniversityEntranceExamSubjectNavi/discussions
    about: 一般的な質問や相談はDiscussionsをご利用ください。
  - name: セキュリティ報告
    url: https://github.com/yourusername/UniversityEntranceExamSubjectNavi/security/policy
    about: セキュリティに関する問題は、セキュリティポリシーに従って報告してください。
  - name: ドキュメント改善
    url: https://github.com/yourusername/UniversityEntranceExamSubjectNavi/tree/main/docs
    about: ドキュメントの改善提案は、docsディレクトリを参照してください。
