# Gitleaks設定ファイル
# このファイルは、リポジトリ内の機密情報を検出するためのルールを定義します。
# 各ルールは、特定のパターンに一致する機密情報を検出するために使用されます。

title = "UniversityEntranceExamSubjectNavi Gitleaks Configuration"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "github-oauth"
description = "GitHub OAuth Token"
regex = '''gho_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "ssh-rsa"
description = "SSH RSA Private Key"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
tags = ["key", "SSH"]

[[rules]]
id = "db-connection"
description = "Database Connection String"
regex = '''(postgres|mysql|mongodb)://[a-zA-Z0-9_]+:[a-zA-Z0-9_]+@[a-zA-Z0-9_.-]+:[0-9]+/[a-zA-Z0-9_]+'''
tags = ["database", "credentials"]
