# Codecovの設定ファイル
# 参考: https://docs.codecov.com/docs/best-practices

codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
  max_report_age: "12h"

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
  require_changes: true
  require_base: true
  require_head: true

coverage:
  precision: 2
  range: "60.0,80.0"
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: true

github_checks:
  annotations: true

slack_app: true

# カバレッジの除外設定
ignore:
  # テストファイル関連
  - "**/*_test.go" # テストファイルを除外
  - "**/testutils/**" # テストユーティリティを除外
  - "**/mocks/**" # モックファイルを除外
  - "back/tests/testutils/**" # テストユーティリティを除外
  - "back/tests/unit/test_data.go" # テストデータファイルを除外
  - "back/tests/unit/benchmarks_test.go" # ベンチマークテストを除外
  - "back/tests/unit/load_test.go" # 負荷テストを除外
  - "back/tests/unit/memory_test.go" # メモリテストを除外
  - "back/tests/unit/example_test.go" # テスト例示ファイルを除外
  - "back/tests/e2e/**" # E2Eテストを除外
  - "back/tests/integration/**" # 統合テストを除外

  # マイグレーション関連
  - "back/migrations/scripts/**" # マイグレーションスクリプトを除外
  - "back/migrations/seeds/**" # シードデータを除外

  # テストデータ関連
  - "back/tests/testdata/**" # テストデータディレクトリを除外

# カバレッジの集計方法
flags:
  unittests:
    paths:
      - back/
      - front/
    carryforward: true # 前回のカバレッジを引き継ぐ
