export const SCORE_CONSTRAINTS = {
  MIN_VALUE: 0,
  MAX_VALUE: 100,
  MIN_WEIGHT: 0,
  MAX_WEIGHT: 1,
  DEFAULT_DECIMAL_PLACES: 2,
} as const;

export const SCORE_ERROR_CODES = {
  INVALID_RANGE: 'INVALID_SCORE_RANGE',
  INVALID_WEIGHT: 'INVALID_WEIGHT',
  CALCULATION_ERROR: 'CALCULATION_ERROR',
} as const;

export const SCORE_ERROR_MESSAGES = {
  [SCORE_ERROR_CODES.INVALID_RANGE]: '点数は0から100の間で入力してください',
  [SCORE_ERROR_CODES.INVALID_WEIGHT]: '重みは0から1の間で入力してください',
  [SCORE_ERROR_CODES.CALCULATION_ERROR]: '計算中にエラーが発生しました',
} as const;
