version: 1.0.0

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - gocritic
    - gocyclo
    - goimports
    - gomnd
    - goprintffuncname
    - gostyle
    - gosystemd
    - gotype
    - gotypex
    - lll
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
