version: "3.8"

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: test-db
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_NAME: test_db
    depends_on:
      test-db:
        condition: service_healthy
    command: go test -v ./...
