openapi: 3.0.0
info:
  title: University Entrance Exam API
  description: 大学入試科目情報を管理するためのAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: 開発サーバー
paths:
  /api/universities:
    get:
      summary: 大学一覧の取得
      description: 全ての大学情報を取得します
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/University"
components:
  schemas:
    University:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        website:
          type: string
        departments:
          type: array
          items:
            $ref: "#/components/schemas/Department"
