import {
  SUBJECT_PATTERNS as SUBJECT_PATTERN_NAMES,
  TEST_TYPE_PATTERNS as TEST_TYPE_PATTERN_NAMES,
} from "./constants/subjectPatterns";

export const SUBJECT_PATTERNS = SUBJECT_PATTERN_NAMES;
export const TEST_TYPE_PATTERNS = TEST_TYPE_PATTERN_NAMES;
