# 共通の環境変数定義
# タイムゾーンと環境設定
x-common-variables: &common-variables
  TZ: Asia/Tokyo
  NODE_ENV: development

# バックエンド固有の環境変数定義
# データベース接続情報とアプリケーション設定
x-backend-variables: &backend-variables
  <<: *common-variables
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: development_db_password
  DB_NAME: university_exam_db
  DB_PORT: 5432
  GO_ENVIRONMENT: development
  CSRF_SECRET: development_csrf_secret
  JWT_SECRET: development_jwt_secret
  DB_SSLMODE: disable
  DB_CONNECTION_TIMEOUT: 10

services:
  # PostgreSQLデータベースサービス
  # データの永続化とヘルスチェックを実装
  postgres:
    image: postgres:16-alpine
    environment:
      <<: *common-variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_db_password
      POSTGRES_DB: university_exam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # バックエンドサービス
  # Goアプリケーションの実行環境
  backend:
    build:
      context: ../../../back
      dockerfile: Dockerfile.dev
      args:
        GO_VERSION: 1.24.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *backend-variables
    volumes:
      - backend_cache:/go/pkg/mod
      - ../../../deployments/docker/development/.env.development:/app/.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "go run migrations/scripts/main.go up &&
             go run migrations/seeds/main.go &&
             go run cmd/api/main.go"

  # フロントエンドサービス
  # Next.jsアプリケーションの実行環境
  frontend:
    build:
      context: ../../../front
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: 20
    volumes:
      - ../../../front:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      <<: *common-variables
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    networks:
      - app-network
    restart: unless-stopped

# 永続化ボリュームの定義
volumes:
  postgres_data: # データベースのデータ永続化
  backend_cache: # Goモジュールのキャッシュ
  frontend_node_modules: # Node.jsモジュールのキャッシュ

# アプリケーション用ネットワークの定義
networks:
  app-network:
    driver: bridge
