x-common-variables: &common-variables
  TZ: Asia/Tokyo
  NODE_ENV: development

x-backend-variables: &backend-variables
  <<: *common-variables
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: university_exam_db
  DB_PORT: 5432
  GO_ENVIRONMENT: development

services:
  postgres:
    image: postgres:16-alpine
    environment:
      <<: *common-variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_exam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ../../../back
      dockerfile: Dockerfile.dev
      args:
        GO_VERSION: 1.21
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *backend-variables
    volumes:
      - ../../../back:/app
      - backend_cache:/go/pkg/mod
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ../../../front
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: 20
    volumes:
      - ../../../front:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      <<: *common-variables
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_cache:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
