name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Goのセットアップ
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          check-latest: true
          cache: true
          cache-dependency-path: back/go.sum

      # golangci-lintのインストール
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: back
          args: ./...

      # バックエンドのlintチェック
      - name: Lint Backend
        run: |
          cd back
          golangci-lint run ./...

      # フロントエンドのlintチェック
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: front/yarn.lock

      - name: Install Frontend Dependencies
        run: |
          cd front
          yarn install --frozen-lockfile

      - name: Lint and Type Check Frontend
        run: |
          cd front
          yarn lint
          yarn type-check

      # Dependency Checkの実行
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "UniversityEntranceExamSubjectNavi"
          path: "."
          format: "SARIF"
          out: "dependency-check-report.sarif"

      # SARIFファイルのアップロード
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check-report.sarif
