name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Goのセットアップ
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          check-latest: true

      # golangci-lintのインストール
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          golangci-lint --version

      # バックエンドのlintチェック
      - name: Lint Backend
        run: |
          cd back
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run ./...

      # フロントエンドのlintチェック
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install Frontend Dependencies
        run: |
          cd front
          yarn install --frozen-lockfile

      - name: Lint and Type Check Frontend
        run: |
          cd front
          yarn lint
          yarn type-check

      # Dependency Checkの実行
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "UniversityEntranceExamSubjectNavi"
          path: "."
          format: "SARIF"
          out: "dependency-check-report.sarif"

      # SARIFファイルのアップロード
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check-report.sarif
