name: Security Checks

on:
  schedule:
    - cron: "0 0 * * *" # 毎日実行
  push:
    branches: [main, develop]
    paths:
      - "**.go"
      - "**.ts"
      - "**.tsx"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
      - "**/go.mod"
      - "**/go.sum"
  pull_request:
    branches: [main, develop]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "UniversityEntranceExamSubjectNavi"
          path: "."
          format: "SARIF"
          out: "./dependency-check-report.sarif"
          args: "--suppression ./.github/dependency-check-suppressions.xml"

      - name: Upload dependency scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "./dependency-check-report.sarif"
          checkout_path: ${{ github.workspace }}
          category: "dependency-check"

  code-scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "go,javascript,typescript"
          queries: security-extended,security-and-quality
          tools: latest

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "code-scanning"

  secret-scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 完全な履歴を取得

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .gitleaks.toml
          redact: true
          verbose: true
          no-git: false
